### ISSUE TITLE
Review Ticket Week 2

### ISSUE THREAD

**Issue by KrishnadevL** [CalrethilOfMirkwood/FOSSite#21]

**Comment by KrishnadevL** [comment]
## Team

### README quality, release day policies, Scrum Board to week after break

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification:

### Deployed Web Site

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification:

**Comment by KrishnadevL** [comment]
## Krish's Individual Ticket 

**About Page must Extend from Layout and have special customization (color pallet, background, etc)**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: The individual page has a[ unique design compared to the original website](https://github.com/CalrethilOfMirkwood/FOSSite/blob/b9352e7dde5093797f45f45e747ce6a6c0be0d43/templates/abt_pages/krish_abt.html#L77-L87) using monochromatic colors to create a simple yet modernistic design. It uses the same font and certain elements of the page [utilize the color scheme present](https://github.com/CalrethilOfMirkwood/FOSSite/blob/9be2b38a7d48119f51c545c82f6ea629a801830c/templates/abt_pages/krish_abt.html#L90) throughout the website. 

**Picture with Mask that toggles to Picture of Choice (ie pic without mask)**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Mask toggle function is [perfectly functional](https://github.com/CalrethilOfMirkwood/FOSSite/blob/9be2b38a7d48119f51c545c82f6ea629a801830c/templates/abt_pages/krish_abt.html#L9-L24) and allows for the user to directly click on the image to change the picture, [no external buttons were necessary](https://github.com/CalrethilOfMirkwood/FOSSite/blob/9be2b38a7d48119f51c545c82f6ea629a801830c/templates/abt_pages/krish_abt.html#L46). 

**Pull or show data (Web API) with information of interest**

- [ ]  1.0
- [x]  .75
- [ ]  .5
- [ ]  0

Justification: A [public API was used and displayed](https://github.com/CalrethilOfMirkwood/FOSSite/blob/9be2b38a7d48119f51c545c82f6ea629a801830c/master.py#L29-L32) however the API was not embedded as creatively as intended and user-interactivity is not present. As such, it wasn't exceeding standards in my case. 

**Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Established links n about pages to[ journal, GitHub issues and create task issue](https://github.com/CalrethilOfMirkwood/FOSSite/blob/9be2b38a7d48119f51c545c82f6ea629a801830c/templates/abt_pages/krish_abt.html#L41-L43), which contains plan and will contain further progress on create task. 

**Create Task plan**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: All [create task planning](https://github.com/CalrethilOfMirkwood/FOSSite/issues/18#issuecomment-989105203) was conducted. It consists of a end goal of the program as well as the technical features that are covered under this potential idea

**2.3 Extracting Information from Data, 2.4 Using Programs with Data**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Both [quizzes](https://docs.google.com/document/d/1Yd2N04Y8EEOolwOF8eyXlXfu_NiOpqE99vexkLGeswg/edit#bookmark=id.tkaym1it04rh) were completed and [TPT notes](https://docs.google.com/document/d/1Yd2N04Y8EEOolwOF8eyXlXfu_NiOpqE99vexkLGeswg/edit#bookmark=id.xppdzotxbp0k) were taken. 

## Overall Individual Scores: 

**5.75/6**

**Comment by CalrethilOfMirkwood** [comment]
## Sophie's Individual Ticket 

**About Page must Extend from Layout and have special customization (color pallet, background, etc)**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: I meet both requirements because [my about page](https://github.com/CalrethilOfMirkwood/FOSSite/blob/master/templates/abt_pages/sophie.html) has both a custom color scheme and includes the base navbar. 

**Picture with Mask that toggles to Picture of Choice (ie pic without mask)**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: I made a [function](https://github.com/CalrethilOfMirkwood/FOSSite/blob/master/templates/abt_pages/sophie.html#L18-L31) that toggles between a picture of me and a sketch I drew on click, the other group members also used this function.

**Pull or show data (Web API) with information of interest**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: I made a [function](https://github.com/CalrethilOfMirkwood/FOSSite/blob/master/silmarillionmemes.py) that gets the raw json data from the subreddit r/silmarillionmemes.  Since all of the posts there are images, I can make the title and the image of the post show up on my about page.

**Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: I  established links in my page to my [ journal and GitHub issues](https://github.com/CalrethilOfMirkwood/FOSSite/blob/master/templates/abt_pages/sophie.html#L42). 

**Create Task plan**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Completed ideation for [create task planning](https://github.com/CalrethilOfMirkwood/FOSSite/issues/13).  I will work in pairs with Valerie.

**2.3 Extracting Information from Data, 2.4 Using Programs with Data**

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [Journal](https://docs.google.com/document/d/1pevIAx6l1T2paGKv7fC8DbOfuA8IS8x0SDsPHH6GK3E/edit?usp=sharing)  I got full score on both quizzes and presented the slides (doubling as my notes) to the class.

## Overall Individual Score: 

**6/6**

**Comment by DistilledVinegar** [comment]
### Val's Individual Ticket

About Page must Extend from Layout and have special customization (color pallet, background, etc)

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Uses navbar and custom color scheme.

Picture with Mask that toggles to Picture of Choice (ie pic without mask)

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: An image alternates between a selfie of me and a drawing of me a friend made when clicked.

Pull or show data (Web API) with information of interest

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: I used an API to pull Bible verses from a website to display them when a button is clicked. Although the same data is shown every time, it is nonetheless being retrieved in real-time from an API.

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Conspicuously placed link to Journal on About me page.

Create Task plan

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Completed ideation for create task planning. I will work in pairs with Sophie.

2.3 Extracting Information from Data, 2.4 Using Programs with Data

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: Quizzes and notes taken as seen in Journal.

Overall Individual Score:
6/6
